# Introduction to NumPy

- **NumPy** is a Python library for doing efficient computation with typed arrays. It is written in C and is much faster than the build in Python data structures. [Documentation](https://docs.scipy.org/doc/numpy/user/basics.html)





## NumPy

Conventioally, NumPy is imported and renamed to **np**

In [0]:
import numpy as np

NumPy allows us to create arrays that are similar to Pythons build in lists

In [0]:
a = [1, 2, 3, 4]  # A Python list
a_np = np.array([1,2,3,4]) # A numpy array

print(a)
print(a_np)

NumPy arrays have a shape that we can query.

In [4]:
a_np.shape

(4,)

In this case we a vector of length four, but we can reshape this if we like.

In [7]:
b=a_np.reshape((2,2))
b

array([[1, 2],
       [3, 4]])

**b** is now a 2x2 matrix. 

We can pick out a specific element with indexes:

In [15]:
b[0][0]

1

Or equivalently:

In [14]:
b[0,0]

1

Or we can get the last column

In [12]:
b[:,1]

array([2, 4])

NumPy arrays have some build in functions, for example we can **sum** all the elements of a structure

In [8]:
b.sum()

10

It is also possible to sum along the first dimension only

In [9]:
b.sum(axis=0)

array([4, 6])

Or in the other dimension

In [10]:
b.sum(axis=1)

array([3, 7])