# Introduction to NumPy

- **NumPy** is a Python library for doing efficient computation with typed arrays. It is written in C and is much faster than the build in Python data structures. [Documentation](https://docs.scipy.org/doc/numpy/user/basics.html)





## NumPy

Conventioally, NumPy is imported and renamed to **np**

In [0]:
import numpy as np

NumPy allows us to create arrays that are similar to Pythons build in lists

In [0]:
a = [1, 2, 3, 4]  # A Python list
a_np = np.array([1,2,3,4]) # A numpy array

print(a)
print(a_np)

[1, 2, 3, 4]
[1 2 3 4]


NumPy arrays have a shape that we can query.

In [0]:
a_np.shape

(4,)

In this case we a vector of length four, but we can reshape this if we like.

In [0]:
b=a_np.reshape((2,2))
b

array([[1, 2],
       [3, 4]])

**b** is now a 2x2 matrix. 

We can turn it back into a vector like this:

In [0]:
b.reshape((4))

array([1, 2, 3, 4])

or a 4x1 matrix:

In [0]:
b.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

If we don't know how many elements we have in one of the dimensions we can replace this dimension with **-1** and NumPy will find it for us:

In [0]:
b.reshape((-1,1))

array([[1],
       [2],
       [3],
       [4]])

We can pick out a specific element with indexes:

In [0]:
b[0][0]

1

Or equivalently:

In [0]:
b[0,0]

1

Or we can get the last column

In [0]:
b[:,1]

array([2, 4])

NumPy arrays have some build in functions, for example we can **sum** all the elements of a structure

In [0]:
b.sum()

10

It is also possible to sum along the first dimension only

In [0]:
b.sum(axis=0)

array([4, 6])

Or in the other dimension

In [0]:
b.sum(axis=1)

array([3, 7])